import {
  listScheduledJobs,
  getEnabledJobs,
  getScheduledJob,
  createScheduledJob,
  updateScheduledJob,
  deleteScheduledJob,
  logSchedulerExecution,
  getRecentSchedulerExecutionLogs,
  getLatestSchedulerFailure,
  getLatestHealthWatchdogEvent,
  type ScheduledJobRow,
  type SchedulerExecutionType,
  type SchedulerExecutionPhase,
  type SchedulerExecutionLogRow,
} from './scheduledJobQueries.js';

import {
  getExternalSession,
  createExternalSession,
  getDefaultNotificationChannel,
  getExternalSessionBySessionId,
  getOrCreateExternalSession,
  updateExternalSessionSessionId,
  addPinnedUserfile,
  getPinnedUserfileIds,
  clearPinnedUserfiles,
  setDefaultNotificationChannel,
  type ExternalSessionRow,
} from './externalSessionQueries.js';

export {
  listScheduledJobs,
  getEnabledJobs,
  getScheduledJob,
  createScheduledJob,
  updateScheduledJob,
  deleteScheduledJob,
  logSchedulerExecution,
  getRecentSchedulerExecutionLogs,
  getLatestSchedulerFailure,
  getLatestHealthWatchdogEvent,
  getExternalSession,
  createExternalSession,
  getDefaultNotificationChannel,
  getExternalSessionBySessionId,
  getOrCreateExternalSession,
  updateExternalSessionSessionId,
  addPinnedUserfile,
  getPinnedUserfileIds,
  clearPinnedUserfiles,
  setDefaultNotificationChannel,
};

export type {
  ScheduledJobRow,
  SchedulerExecutionType,
  SchedulerExecutionPhase,
  SchedulerExecutionLogRow,
  ExternalSessionRow,
};
